### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by kpax2049** [schwinguin/chatchamp#3]
I'm trying to run this project in a Mac environment but getting error messages when trying to start the server:

> (myenv) kpax chatchamp (main) >> python3 --version
Python 3.9.6
(myenv) kpax chatchamp (main) >> pip3 --version
pip 24.3.1 from /Users/kpax/Projects/chatchamp/myenv/lib/python3.9/site-packages/pip (python 3.9)

> 

`(myenv) kpax chatchamp (main) >> python3 chatChamp_Server.py
(89555) wsgi starting up on http://0.0.0.0:5554
(89555) wsgi exited, is_accepting=True
Traceback (most recent call last):
  File "/Users/kpax/Projects/chatchamp/chatChamp_Server.py", line 545, in <module>
    admin.start_flask_app(app, settings['host'], int(settings['port']), settings['debug'], settings['ssl'], settings['cert_file'], settings['key_file'])
  File "/Users/kpax/Projects/chatchamp/admin.py", line 444, in start_flask_app
    eventlet.wsgi.server(eventlet_socket, app)
  File "/Users/kpax/Projects/chatchamp/myenv/lib/python3.9/site-packages/eventlet/wsgi.py", line 1071, in server
    client_socket, client_addr = sock.accept()
  File "/Users/kpax/Projects/chatchamp/myenv/lib/python3.9/site-packages/eventlet/greenio/base.py", line 228, in accept
    self._trampoline(fd, read=True, timeout=self.gettimeout(), timeout_exc=_timeout_exc)
  File "/Users/kpax/Projects/chatchamp/myenv/lib/python3.9/site-packages/eventlet/greenio/base.py", line 206, in _trampoline
    return trampoline(fd, read=read, write=write, timeout=timeout,
  File "/Users/kpax/Projects/chatchamp/myenv/lib/python3.9/site-packages/eventlet/hubs/__init__.py", line 153, in trampoline
    listener = hub.add(hub.READ, fileno, current.switch, current.throw, mark_as_closed)
  File "/Users/kpax/Projects/chatchamp/myenv/lib/python3.9/site-packages/eventlet/hubs/kqueue.py", line 52, in add
    self._control([event], 0, 0)
  File "/Users/kpax/Projects/chatchamp/myenv/lib/python3.9/site-packages/eventlet/hubs/kqueue.py", line 38, in _control
    return self.kqueue.control(events, max_events, timeout)
TypeError: changelist must be an iterable of select.kevent objects`

**Comment by kpax2049** [comment]
I was finally able to run the App but only through the Python Debugger plugin in VS Code. I'm still seeing error messages if I try from the Terminal.
